version: "3.8"

services:
  matrix-maubot:
    container_name: matrix-maubot
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    image: dock.mau.dev/maubot/maubot:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.matrix-maubot.entrypoints: "websecure"
      traefik.http.routers.matrix-maubot.rule: "Host(`chat.${DOMAIN}`) && PathPrefix(`/_matrix/maubot/`)"
      traefik.http.routers.matrix-maubot.service: "matrix-maubot"
      traefik.http.routers.matrix-maubot.tls.certresolver: "letsencrypt"
      traefik.http.services.matrix-maubot.loadbalancer.server.port: "29316"
    volumes:
      - "./maubot/data:/data:z"

networks:
  external:
    external: true
    name: $NETWORK
